### ISSUE TITLE
If i click on button player or something else minecraft is crashing, i used it on crystalpvp.cc and mapped everything but it still crashes

### ISSUE THREAD

**Issue by RomchickHHH** [humboldt123/NoteBot#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RomchickHHH** [comment]
pls help and contact me discord Rom#2414

**Comment by humboldt123** [comment]
@Victormeriqui can you comment here so I can assign you.
[Log File](https://cdn.discordapp.com/attachments/735692846425702403/735880846883553280/latest.log)

**Comment by Victormeriqui** [comment]
Yes sure

**Comment by humboldt123** [comment]
Alright I assigned you. I genuinely have no idea why is game is crashing.

**Comment by Victormeriqui** [comment]
> Alright I assigned you. I genuinely have no idea why is game is crashing.

Will investigate over the weekend

**Comment by humboldt123** [comment]
Thank you.

**Comment by Victormeriqui** [comment]
Issue was caused because the folders the mod uses to look for files to convert/edit` (.../minecraft/NoteBot/ToConvert & .../minecraft/NoteBot/Converted)` didn't exist

Added automatic creation, should work when https://github.com/humboldt123/NoteBot/pull/2#issue-456829323 gets merged
